// <auto-generated />
using System;
using GrpcService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcService.Migrations
{
    [DbContext(typeof(GrpcDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcService.Models.GrpcData", b =>
                {
                    b.Property<int>("PacketSeqNum")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("RecordSeqNum")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Decimal1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Decimal2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Decimal3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Decimal4")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PacketTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PacketSeqNum", "RecordSeqNum");

                    b.ToTable("GrpcData");
                });
#pragma warning restore 612, 618
        }
    }
}
